# Generated by Django 5.0.6 on 2024-06-20 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datastreams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('reading', models.FloatField(null=True)),
                ('datastream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datastreams.datastream')),
            ],
            options={
                'db_table': 'readings',
            },
        ),
        migrations.RunSQL(
            """
            SELECT create_hypertable('readings', 'timestamp');
            """,
            reverse_sql="""
                DROP TABLE readings;
            """
        )
    ]
